# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: ls
    displayName: 'Check folders'

  - script: echo $PWD
    displayName: 'Check path'
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '20.10.5'

  - script: docker run -v $PWD:/project -w /project espressif/idf idf.py build
    displayName: 'Build project using espressif/idf image'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$PWD/build/esp32.bin'
      artifact: 'esp32.bin'
      publishLocation: 'pipeline'
